
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uniportal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: uniportal
  template:
    metadata:
      labels:
        app: uniportal
    spec:
      containers:
      - name: uniportal
        image: university-portal:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: RUN_MODE
          value: "Kubernetes"
        - name: APP_SECRET
          value: "change-me"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "200Mi"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 2
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: uniportal-svc
spec:
  selector:
    app: uniportal
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000

